pipeline{ 
  agent any
  parameters{
    string(name: 'BRANCH_BUILD', defaultValue: 'master', description: 'Branch to build')
    string(name: 'WORKDIR', defaultValue: 'docker-demo', description: 'Where a git will clone into')
    string(name: 'GIT_URL', defaultValue: '', description: 'Git URL of project to build')
  }
  stages{
    stage("Checkout SCM"){

      step{

        dir("${WORKDIR}"){
          checkout([
            $class: 'GitSCM',
            branches: [[name: "${BRANCH_BUILD}"]],
            userRemoteConfigs: [[url: "${GIT_URL}"]]
          ])  
        }
      }
    }
  }
  post {
      always {
          deleteDir()
      }
    }
}
