version: 2.1
orbs: 
  welcome: circleci/welcome-orb@0.4.1

jobs: 
  build: 
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - run: 
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="FOO"' >> "$BASH_ENV" 
      - run: 
          name: "What is my custom environment variables"
          command: echo ${MY_ENV_VAR}
  print_hello: 
    docker: 
      - image:  circleci/node:13.8.0
    steps:
      - run: 
          name: Print Hello
          command: |
            echo "hello"
  print_world: 
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: 
          name: Print World
          command: | 
            echo "worlds"
  deploy: 
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - run: 
          name: Deploy 
          command: | 
            echo "Tui dang deploy ne"   

workflows: 
  welcome: 
    jobs: 
      - welcome/run
      - build: 
          requires: 
            - "welcome/run"
      - print_hello:
          requires:
            - "build"
      - print_world: 
          requires:
            - "print_hello"
      - deploy: 
          requires: 
            - "print_world"